import type { EarthquakeEvent, Language, Translations } from './types';

export const INDIAN_CITIES = [
    { city: "Delhi", state: "Delhi", lat: 28.6139, lon: 77.2090 },
    { city: "Mumbai", state: "Maharashtra", lat: 19.0760, lon: 72.8777 },
    { city: "Bengaluru", state: "Karnataka", lat: 12.9716, lon: 77.5946 },
    { city: "Kolkata", state: "West Bengal", lat: 22.5726, lon: 88.3639 },
    { city: "Chennai", state: "Tamil Nadu", lat: 13.0827, lon: 80.2707 },
    { city: "Hyderabad", state: "Telangana", lat: 17.3850, lon: 78.4867 },
    { city: "Ahmedabad", state: "Gujarat", lat: 23.0225, lon: 72.5714 },
    { city: "Pune", state: "Maharashtra", lat: 18.5204, lon: 73.8567 },
    { city: "Jaipur", state: "Rajasthan", lat: 26.9124, lon: 75.7873 },
    { city: "Lucknow", state: "Uttar Pradesh", lat: 26.8467, lon: 80.9462 },
    { city: "Guwahati", state: "Assam", lat: 26.1445, lon: 91.7362 },
    { city: "Srinagar", state: "Jammu and Kashmir", lat: 34.0837, lon: 74.7973 },
    { city: "Bhuj", state: "Gujarat", lat: 23.2537, lon: 69.6669 },
];

export const INITIAL_EVENTS: EarthquakeEvent[] = [
    {
        id: 1,
        magnitude: 5.6,
        depth: 10,
        location: { lat: 23.25, lon: 69.67, city: "Bhuj", state: "Gujarat" },
        timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
        severity: "Moderate"
    },
    {
        id: 2,
        magnitude: 4.2,
        depth: 25,
        location: { lat: 26.14, lon: 91.73, city: "Guwahati", state: "Assam" },
        timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
        severity: "Low"
    },
    {
        id: 3,
        magnitude: 6.1,
        depth: 15,
        location: { lat: 34.08, lon: 74.80, city: "Srinagar", state: "Jammu and Kashmir" },
        timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
        severity: "Severe"
    }
];



export const TRANSLATIONS: Translations = {
    en: {
        title: "AI Earthquake Alert System - India",
        dashboardTitle: "Live Seismic Dashboard",
        liveSeismicMap: "Live Seismic Map",
        realTimeAlerts: "Real-time Alerts",
        eventDetails: "Event Details",
        magnitude: "Magnitude",
        depth: "Depth",
        location: "Location",
        time: "Time",
        severity: "Severity",
        generateAdvisory: "Generate AI Advisory",
        generating: "Generating...",
        advisory: "AI-Generated Public Advisory",
        noEventSelected: "Select an event to see details.",
        recentEvents: "Recent Events",
        highestMagnitude: "Highest Magnitude (24h)",
        mostActiveRegion: "Most Active Region",
        km: "km",
        subscribe: "Subscribe",
        subscribing: "Subscribing...",
        enterPhoneNumber: "+919876543210",
        invalidPhoneNumber: "Please enter a valid Indian mobile number (e.g., +919876543210).",
        subscriptionFailed: "Failed to subscribe. Please try again.",
        subscribed: "Subscribed",
        unsubscribe: "Unsubscribe",
        unsubscribeFailed: "Failed to unsubscribe. Please try again.",
        confirmUnsubscription: "Confirm Unsubscription",
        cancel: "Cancel",
        confirm: "Confirm",
        goToLocation: "Go to Location",
        searchPlaceholder: "Search by city or state...",
        filterBySeverity: "Filter by Severity",
        filterByMagnitude: "Filter by Magnitude",
        filterByTime: "Filter by Time",
        last24h: "Last 24h",
        all: "All",
        low: "Low",
        moderate: "Moderate",
        severe: "Severe",
        moreInfo: "More Info",
        feltReports: "Felt Reports",
        seismicWaveData: "Seismic Wave Data",
        learnMore: "Learn More at NDMA",
        weatherConditions: "Weather Conditions",
        temperature: "Temperature",
        wind: "Wind",
        loadingWeather: "Loading weather...",
        weatherError: "Failed to load weather.",
        suggestEvacuationRoute: "Suggest Evacuation Route",
        suggestingRoute: "Suggesting...",
        evacuationRoute: "AI-Suggested Evacuation Route",
        viewOnMap: "View on Google Maps",
        aiReasoning: "AI Reasoning",
        toggleHeatmap: "Toggle Heatmap",
        toggleFaultlines: "Toggle Fault Lines",
        generateSafetyTips: "Generate Safety Tips",
        generatingTips: "Generating Tips...",
        aiSafetyTips: "AI-Generated Safety Tips",
        settings: "Settings",
        alertThreshold: "Minimum Magnitude for Alerts",
        alertSound: "Alert Sound",
        soundNone: "None",
        soundBeep: "Beep",
        soundChime: "Chime",
        soundUrgent: "Urgent",
        close: "Close",
        liveDashboard: "Live Dashboard",
        historicalExplorer: "Historical Explorer",
        dateRange: "Date Range",
        magnitudeRange: "Magnitude Range",
        applyFilters: "Apply Filters",
        noHistoricalData: "No historical data found for the selected filters.",
        theme: "Theme",
        lightMode: "Light Mode",
        darkMode: "Dark Mode",
        mapUnavailableTitle: "Map Service Unavailable",
        mapUnavailableMessage: "There was an issue loading the map service. This may be due to a connection issue or a service misconfiguration.",
        refresh: "Refresh Page",
        noAlertsSent: "No alerts have been sent recently.",
        severeAlertTitle: "SEVERE EARTHQUAKE WARNING",
        dropCoverHold: "Drop, Cover, and Hold On!",
        broadcastControlCenter: "Broadcast Control Center",
        pendingApproval: "Pending Approval",
        sendBroadcast: "Send Broadcast",
        sending: "Sending...",
        broadcastSentTo: "Broadcast sent successfully",
        broadcastFailed: "Broadcast Failed",
        retry: "Retry",
        noAlertsQueued: "No alerts are currently queued for broadcast.",
        realtimePushNotifications: "Real-time Push Notifications",
        pushNotificationsDescription: "Get instant earthquake alerts delivered to your phone using the free ntfy.sh service. No sign-up required.",
        yourUniqueChannel: "Your Unique Notification Channel",
        ntfyInstructionsTitle: "How to Subscribe:",
        ntfyInstruction1: "Download the 'ntfy' app on your phone.",
        ntfyInstruction2: "Subscribe to the topic URL shown below.",
        ntfyInstruction3: "Approve broadcasts in the Control Center to get real alerts!",
        scanToSubscribe: "Scan QR to Subscribe",
        // FIX: Add translations for MockPhoneDisplay component
        alertPreview: "Alert Preview",
        officialChannel: "Official Alert Channel",
        waitingForAlert: "Waiting for the next severe alert to be broadcast...",
        sentAlertsLog: "Sent Alerts Log",
        // FIX: Add translations for sent alerts log
        sentTo: "Sent to",
        recipients_plural: "recipients",
        // Admin Dashboard Translations
        adminDashboardTitle: "Admin Dashboard",
        returnToUserDashboard: "Return to User View",
        liveSystemStats: "Live System Stats",
        totalEvents: "Total Events (Live)",
        whatsappSubscribers: "WhatsApp Subscribers",
        smsSubscribers: "SMS Subscribers",
        whatsappAlertsSent: "WhatsApp Alerts Sent (24h)",
        smsAlertsSent: "SMS Alerts Sent (24h)",
        systemHealth: "System Health",
        apiService: "API Service",
        databaseConnection: "Database (MongoDB)",
        whatsappGateway: "WhatsApp Gateway",
        smsGateway: "SMS Gateway",
        operational: "Operational",
        degraded: "Degraded",
        outage: "Outage",
        latency: "Latency",
        ms: "ms",
        alertLog: "Alert Log (Severe Events)",
        recipients: "Recipients",
        alertType: "Type",
        userReports: "User Reports",
        acknowledge: "Acknowledge",
        acknowledged: "Acknowledged",
        acknowledgeAll: "Acknowledge All",
        mlModelStatus: "ML Model Status",
        modelAccuracy: "Model Accuracy",
        lastTrained: "Last Trained",
        retrainingInProgress: "Retraining in progress...",
        retrainModel: "Retrain Model",
        statusIdle: "Idle",
        statusTrained: "Trained & Active",
        never: "Never",
        manualRetrain: "Manual Retrain",
        exportData: "Export Data",
        exportAlertsOnly: "Export Alerts Only",
        exportReportsOnly: "Export Reports Only",
        exportBoth: "Export Both",
        retrainSuccess: "AI model successfully retrained! New accuracy: {accuracy}%.",
        retrainFailed: "AI model retraining failed. Please check the logs and try again.",
        smsAlertManager: "SMS Alert Manager",
        selectEventForAlert: "Select a recent severe event to create an alert:",
        noSevereEvents: "No recent severe events to report.",
        messagePreview: "Message Preview",
        targetSubscribers: "Target Subscribers",
        subscriberCount: "Number of subscribers",
        sendSmsAlert: "Send SMS Alert",
        sendingSms: "Sending SMS...",
        smsSentSuccess: "SMS alert has been dispatched successfully.",
        smsSentFailed: "Failed to dispatch SMS alert.",
        communicationCenter: "Communication Center",
        standardAlertTab: "Standard Alert",
        aiCounselorTab: "AI Counselor",
        generateAiAdvisory: "Generate AI Advisory",
        generatingAiAdvisory: "Generating...",
        // FIX: Add translations for FamilySafetyTracker component.
        familySafetyTracker: "Family Safety Tracker",
        markSafe: "I'm Safe",
        markHelp: "Need Help",
        gettingLocation: "Getting location...",
        locationPermissionDenied: "Location access denied.",
        shareLocation: "Share Location",
        locationShared: "Location Copied!",
        // FIX: Add translations for LoginModal.
        loginTitle: "Admin Login",
        login: "Login",
        loginFailed: "Login failed. Please check your username and password.",
        username: "Username",
        password: "Password",
        smsAlerts: "SMS Alerts",
        smsDescription: "Get critical alerts via SMS. Standard messaging rates may apply.",
        unsubscribing: "Unsubscribing...",
        subscriptionSuccessful: "You have been successfully subscribed!",
    },
    hi: {
        title: "एआई भूकंप चेतावनी प्रणाली - भारत",
        dashboardTitle: "लाइव भूकंपीय डैशबोर्ड",
        liveSeismicMap: "लाइव भूकंपीय मानचित्र",
        realTimeAlerts: "रीयल-टाइम अलर्ट",
        eventDetails: "घटना का विवरण",
        magnitude: "परिमाण",
        depth: "गहराई",
        location: "स्थान",
        time: "समय",
        severity: "गंभीरता",
        generateAdvisory: "एआई सलाह उत्पन्न करें",
        generating: "उत्पन्न हो रहा है...",
        advisory: "एआई-जनित सार्वजनिक सलाह",
        noEventSelected: "विवरण देखने के लिए एक घटना का चयन करें।",
        recentEvents: "हाल की घटनाएँ",
        highestMagnitude: "उच्चतम परिमाण (24 घंटे)",
        mostActiveRegion: "सबसे सक्रिय क्षेत्र",
        km: "किमी",
        subscribe: "सब्सक्राइब करें",
        subscribing: "सब्सक्राइब हो रहा है...",
        enterPhoneNumber: "+919876543210",
        invalidPhoneNumber: "कृपया एक मान्य भारतीय मोबाइल नंबर दर्ज करें (उदा., +919876543210)।",
        subscriptionFailed: "सदस्यता लेने में विफल। कृपया पुन: प्रयास करें।",
        subscribed: "सब्सक्राइब किया हुआ",
        unsubscribe: "अनसब्सक्राइब करें",
        unsubscribeFailed: "अनसब्सक्राइब करने में विफल। कृपया पुन: प्रयास करें।",
        confirmUnsubscription: "अनसब्सक्राइब की पुष्टि करें",
        cancel: "रद्द करें",
        confirm: "पुष्टि करें",
        goToLocation: "स्थान पर जाएं",
        searchPlaceholder: "शहर या राज्य द्वारा खोजें...",
        filterBySeverity: "गंभीरता से फ़िल्टर करें",
        filterByMagnitude: "परिमाण से फ़िल्टर करें",
        filterByTime: "समय से फ़िल्टर करें",
        last24h: "पिछले 24 घंटे",
        all: "सभी",
        low: "कम",
        moderate: "मध्यम",
        severe: "गंभीर",
        moreInfo: "और जानकारी",
        feltReports: "महसूस की गई रिपोर्ट",
        seismicWaveData: "भूकंपीय तरंग डेटा",
        learnMore: "एनडीएमए पर और जानें",
        weatherConditions: "मौसम की स्थिति",
        temperature: "तापमान",
        wind: "हवा",
        loadingWeather: "मौसम लोड हो रहा है...",
        weatherError: "मौसम लोड करने में विफल।",
        suggestEvacuationRoute: "निकासी मार्ग सुझाएं",
        suggestingRoute: "सुझाया जा रहा है...",
        evacuationRoute: "एआई-सुझाया गया निकासी मार्ग",
        viewOnMap: "गूगल मैप्स पर देखें",
        aiReasoning: "एआई तर्क",
        toggleHeatmap: "हीटमैप टॉगल करें",
        toggleFaultlines: "फॉल्ट लाइन्स टॉगल करें",
        generateSafetyTips: "सुरक्षा युक्तियाँ उत्पन्न करें",
        generatingTips: "युक्तियाँ उत्पन्न हो रही हैं...",
        aiSafetyTips: "एआई-जनित सुरक्षा युक्तियाँ",
        settings: "सेटिंग्स",
        alertThreshold: "अलर्ट के लिए न्यूनतम परिमाण",
        alertSound: "अलर्ट ध्वनि",
        soundNone: "कोई नहीं",
        soundBeep: "बीप",
        soundChime: "झंकार",
        soundUrgent: "तत्काल",
        close: "बंद करें",
        liveDashboard: "लाइव डैशबोर्ड",
        historicalExplorer: "ऐतिहासिक एक्सप्लोరర్",
        dateRange: "तिथि सीमा",
        magnitudeRange: "परिमाण सीमा",
        applyFilters: "फ़िल्टर लागू करें",
        noHistoricalData: "चयनित फ़िल्टर के लिए कोई ऐतिहासिक डेटा नहीं मिला।",
        theme: "थीम",
        lightMode: "लाइट मोड",
        darkMode: "डार्क मोड",
        mapUnavailableTitle: "मानचित्र सेवा अनुपलब्ध",
        mapUnavailableMessage: "मानचित्र सेवा लोड करने में कोई समस्या हुई। यह कनेक्शन समस्या या सेवा गलत कॉन्फ़िगरेशन के कारण हो सकता है।",
        refresh: "पेज रीफ़्रेश करें",
        noAlertsSent: "हाल ही में कोई अलर्ट नहीं भेजा गया है।",
        severeAlertTitle: "गंभीर भूकंप की चेतावनी",
        dropCoverHold: "झुको, ढको, और पकड़ो!",
        broadcastControlCenter: "प्रसारण नियंत्रण केंद्र",
        pendingApproval: "अनुमोदन लंबित है",
        sendBroadcast: "प्रसारण भेजें",
        sending: "भेज रहा है...",
        broadcastSentTo: "प्रसारण सफलतापूर्वक भेजा गया",
        broadcastFailed: "प्रसारण विफल",
        retry: "पुनः प्रयास करें",
        noAlertsQueued: "वर्तमान में प्रसारण के लिए कोई अलर्ट कतार में नहीं है।",
        realtimePushNotifications: "रीयल-टाइम पुश सूचनाएं",
        pushNotificationsDescription: "मुफ्त ntfy.sh सेवा का उपयोग करके अपने फोन पर तत्काल भूकंप अलर्ट प्राप्त करें। कोई साइन-अप आवश्यक नहीं है।",
        yourUniqueChannel: "आपका अनूठा सूचना चैनल",
        ntfyInstructionsTitle: "सदस्यता कैसे लें:",
        ntfyInstruction1: "अपने फोन पर 'ntfy' ऐप डाउनलोड करें।",
        ntfyInstruction2: "नीचे दिखाए गए विषय URL की सदस्यता लें।",
        ntfyInstruction3: "वास्तविक अलर्ट प्राप्त करने के लिए नियंत्रण केंद्र में प्रसारण को मंजूरी दें!",
        scanToSubscribe: "सदस्यता के लिए QR स्कैन करें",
        // FIX: Add translations for MockPhoneDisplay component
        alertPreview: "अलर्ट पूर्वावलोकन",
        officialChannel: "आधिकारिक चेतावनी चैनल",
        waitingForAlert: "अगले गंभीर अलर्ट के प्रसारण की प्रतीक्षा है...",
        sentAlertsLog: "भेजे गए अलर्ट लॉग",
        // FIX: Add translations for sent alerts log
        sentTo: "को भेजा गया",
        recipients_plural: "प्राप्तकर्ताओं",
        adminDashboardTitle: "एडमिन डैशबोर्ड",
        returnToUserDashboard: "उपयोगकर्ता व्यू पर लौटें",
        liveSystemStats: "लाइव सिस्टम आँकड़े",
        totalEvents: "कुल घटनाएँ (लाइव)",
        whatsappSubscribers: "व्हाट्सएप सब्सक्राइबर्स",
        smsSubscribers: "SMS सब्सक्राइबर्स",
        whatsappAlertsSent: "व्हाट्सएप अलर्ट भेजे गए (24घं)",
        smsAlertsSent: "SMS अलर्ट भेजे गए (24घं)",
        systemHealth: "सिस्टम स्वास्थ्य",
        apiService: "एपीआई सेवा",
        databaseConnection: "डेटाबेस (मोंगोडीबी)",
        whatsappGateway: "व्हाट्सएप गेटवे",
        smsGateway: "SMS गेटवे",
        operational: "चालू",
        degraded: "खराब प्रदर्शन",
        outage: "आउटेज",
        latency: "विलंबता",
        ms: "मिसे",
        alertLog: "अलर्ट लॉग (गंभीर घटनाएँ)",
        recipients: "प्राप्तकर्ता",
        alertType: "प्रकार",
        userReports: "उपयोगकर्ता रिपोर्ट",
        acknowledge: "स्वीकार करें",
        acknowledged: "स्वीकृत",
        acknowledgeAll: "सभी को स्वीकार करें",
        mlModelStatus: "एमएल मॉडल स्थिति",
        modelAccuracy: "मॉडल सटीकता",
        lastTrained: "अंतिम प्रशिक्षित",
        retrainingInProgress: "पुनर्प्रशिक्षण जारी है...",
        retrainModel: "मॉडल को पुनः प्रशिक्षित करें",
        statusIdle: "निष्क्रिय",
        statusTrained: "प्रशिक्षित और सक्रिय",
        never: "कभी नहीं",
        manualRetrain: "मैनुअल पुनर्प्रशिक्षण",
        exportData: "डेटा निर्यात करें",
        exportAlertsOnly: "केवल अलर्ट निर्यात करें",
        exportReportsOnly: "केवल रिपोर्ट निर्यात करें",
        exportBoth: "दोनों निर्यात करें",
        retrainSuccess: "एआई मॉडल सफलतापूर्वक पुनः प्रशिक्षित! नई सटीकता: {accuracy}%।",
        retrainFailed: "एआई मॉडल पुनर्प्रशिक्षण विफल रहा। कृपया लॉग जांचें और पुनः प्रयास करें।",
        smsAlertManager: "एसएमएस अलर्ट मैनेजर",
        selectEventForAlert: "अलर्ट बनाने के लिए हाल की गंभीर घटना का चयन करें:",
        noSevereEvents: "रिपोर्ट करने के लिए कोई हाल की गंभीर घटनाएं नहीं हैं।",
        messagePreview: "संदेश पूर्वावलोकन",
        targetSubscribers: "लक्ष्य ग्राहक",
        subscriberCount: "ग्राहकों की संख्या",
        sendSmsAlert: "एसएमएस अलर्ट भेजें",
        sendingSms: "एसएमएस भेजा जा रहा है...",
        smsSentSuccess: "एसएमएस अलर्ट सफलतापूर्वक भेज दिया गया है।",
        smsSentFailed: "एसएमएस अलर्ट भेजने में विफल।",
        communicationCenter: "संचार केंद्र",
        standardAlertTab: "मानक अलर्ट",
        aiCounselorTab: "एआई काउंसलर",
        generateAiAdvisory: "एआई सलाह उत्पन्न करें",
        generatingAiAdvisory: "उत्पन्न हो रहा है...",
        // FIX: Add translations for FamilySafetyTracker component.
        familySafetyTracker: "परिवार सुरक्षा ट्रैकर",
        markSafe: "मैं सुरक्षित हूँ",
        markHelp: "मदद चाहिए",
        gettingLocation: "स्थान प्राप्त हो रहा है...",
        locationPermissionDenied: "स्थान की अनुमति नहीं है।",
        shareLocation: "स्थान साझा करें",
        locationShared: "स्थान कॉपी किया गया!",
        // FIX: Add translations for LoginModal.
        loginTitle: "एडमिन लॉगिन",
        login: "लॉगिन करें",
        loginFailed: "लॉगिन विफल। कृपया अपना उपयोगकर्ता नाम और पासवर्ड जांचें।",
        username: "उपयोगकर्ता नाम",
        password: "पासवर्ड",
        smsAlerts: "एसएमएस अलर्ट",
        smsDescription: "एसएमएस के माध्यम से महत्वपूर्ण अलर्ट प्राप्त करें। मानक संदेश दरें लागू हो सकती हैं।",
        unsubscribing: "अनसब्सक्राइब हो रहा है...",
        subscriptionSuccessful: "आपकी सदस्यता सफलतापूर्वक हो गई है!",
    },
};
